<a href="https://colab.research.google.com/github/ltocasuche/Metodos1_Fernando_Bareno_Y_Laura_Tocasuche/blob/main/Lineal.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#PUNTO 1 (TEORICO)

- Relacion 1:                  

  Xn+1 = 4Xn - Xn^2,
  X0 = 4sin^2(theta)

  Solución general: Xn+1 = 4sin^2(2^(n+1)(theta))

- Relacion 2:

  Xn+1 = 4Xn - 4Xn^2,
  X0 = sin^2(theta)

  Solución general: Xn+1 = sin^2(2^(n+1)(theta))

*Demostrar que la solución general se cumple para cada relación:*

**Relación 1:**

*se cumple para n = 0?*

X0+1 = 4X0 - X0^2

X1 = 4(4sin^2(theta)) - (4sin^2(theta))^2

= 16sin^2(theta) - 16sin^4(theta)
= 16sin^2(theta)(1-sin^2(theta))
= 16sin^2(theta)cos^2(theta)

= 4(2sin(theta)cos(theta))^2
= 4sin^2(2(theta))

*probar la solución general:* X0+1 = 4sin^2(2^(0+1)(theta)) = 4sin^2(2(theta))

*si se cumple, ahora suponemos que la formula es cierta para un n arbitrario.*
Xn = 4sin^2(2^(n)(theta)), *demostrar si esta es cierta para n+1.*

Xn+1 = 4(4sin^2(2^n(theta))) - (4sin^2(2^n(theta)))^2

= 16sin^2(2^n(theta)) - 16sin^4(2^n(theta))
= 16sin^2(2^n(theta))(1-sin^2(2^n(theta)))
= 16sin^2(2^n(theta))cos^2(2^n(theta))

= 4(2sin(2^n(theta))cos(2^n(theta)))^2
= 4sin^2(2^(n+1)(theta))

**si se cumple.**

**Relación 2:**

*se cumple para n = 0?*

X0+1 = 4X0 - 4X0^2

X1 = 4sin^2(theta) - 4(sin^2(theta))^2
=  4sin^2(theta) - 4sin^4(theta)

= 4sin^2(theta)(1-sin^2(theta))
= 4sin^2(theta)cos^2(theta)

= (2sin(theta)cos(theta))^2
= sin^2(2(theta))

*probar la solución general:* X0+1 = sin^2(2^(0+1)(theta)) = sin^2(2(theta))

*si se cumple, ahora suponemos que la formula es cierta para un n arbitrario.*
Xn = sin^2(2^n(theta)), *demostrar si esta es cierta para n+1.*

Xn+1 = 4(sin^2(2^n(theta))) - 4(sin^2(2^n(theta)))^2

= 4sin^2(2^n(theta)) - 4sin^4(2^n(theta))
= 4sin^2(2^n(theta))(1-sin^2(2^n(theta)))
= 4sin^2(2^n(theta))cos^2(2^n(theta))

= (2sin(2^n(theta))cos(2^n(theta)))^2
= sin^2(2^(n+1)(theta))

**si se cumple.**

In [ ]:
#PUNTO 2

In [ ]:
import numpy as np

In [ ]:
A = np.array([[3.,-1.,-1.],[-1.,3.,1.],[2.,1.,4.]])
A

array([[ 3., -1., -1.],
       [-1.,  3.,  1.],
       [ 2.,  1.,  4.]])

In [ ]:
b = np.array([1.,3.,7.])
b

array([1., 3., 7.])

In [ ]:
np.linalg.solve(A,b)

array([1., 1., 1.])

In [ ]:
#implementar gaus-seidel

def Gauss_Seidel(A,b,x0, itmax = 100, tolerancia = 1e-16):

  x = x0.copy()
  it = 0
  for it in range(itmax):

    x_new = np.copy(x)

    for i in range(A.shape[0]):
      suma = 0.
      for j in range(A.shape[1]):
        if i != j:
          suma += A[i,j]*x_new[j]
          x_new[i] = (b[i] - suma)/A[i,i]

    if np.linalg.norm( np.dot(A,x_new)-b) < tolerancia:
      break

    x = np.copy(x_new)
    it += 1

  print(it)
  return x,it

In [ ]:
x0 = np.array([0.,0.,0.])
x,_ = Gauss_Seidel(A,b,x0)
print(x)

25
[1. 1. 1.]


In [ ]:
#PUNTO 3

In [ ]:
class Solucionador:

    def __init__(self, A, b, tolerancia=1e-16, it_max =100):

        self.A = A
        self.b = b
        self.tolerancia = tolerancia
        self.it_max = it_max

    def jacobi(self):

        x = x0.copy()
        iter = 0

        for it in range(self.it_max):
          x_new = np.copy(x)

          for i in range(self.A.shape[0]):
            suma = 0.
            for j in range(self.A.shape[1]):
              if i != j:
                suma += self.A[i,j]*x[j]
                x_new[i] = (self.b[i] - suma)/self.A[i,i]


          if np.linalg.norm( np.dot(self.A,x_new)-b) < self.tolerancia:
             break

          x = np.copy(x_new)
          iter += 1

        print(x,iter)

        return x, iter

    def gauss_seidel(self):

        x = x0.copy()
        iter = 0

        for it in range(self.it_max):
          x_new = np.copy(x)

          for i in range(self.A.shape[0]):
            suma = 0.
            for j in range(self.A.shape[1]):
              if i != j:
                suma += self.A[i,j]*x_new[j]
                x_new[i] = (self.b[i] - suma)/self.A[i,i]

          if np.linalg.norm( np.dot(self.A,x_new)-b) < self.tolerancia:
            break

          x = np.copy(x_new)
          iter += 1

        print(x,iter)
        return x,iter

In [ ]:
A = np.array([[3.,-1.,-1.],[-1.,3.,1.],[2.,1.,4.]])
b = np.array([1.,3.,7.])
x0 = np.array([0.,0.,0.])
clase = Solucionador(A, b)
x_jacobi = clase.jacobi()
x_gauss_seidel = clase.gauss_seidel()


[1. 1. 1.] 34
[1. 1. 1.] 25


In [ ]:
#PUNTO 4

In [ ]:
def multiplicar_matrices(A,B):

  if A.shape[1] != B.shape[0]:
        raise ValueError("Las matrices no pueden ser multiplicadas.")

  C = np.zeros_like(A)

  for i in range(A.shape[0]):
        for j in range(B.shape[1]):
            for k in range(A.shape[1]):
                C[i][j] += A[i][k] * B[k][j]

  return C

In [ ]:
A = np.array([[1.,0.,0.],[5.,1.,0.],[-2.,3.,1.]])
B = np.array([[4.,-2.,1.],[0.,3.,7.],[0.,0.,2.]])

multiplicación = multiplicar_matrices(A,B)
print(multiplicación)

[[ 4. -2.  1.]
 [20. -7. 12.]
 [-8. 13. 21.]]


In [ ]:
#PUNTO 5 (TEORICO)

A partir del sistema de ecuaciones Ax = b donde A es una matriz triangular inferior, x es un vector y b un vector de terminos independientes.

Para cada fila i, la ecuación se puede expresar como:

Ai1x1 + Ai2x2 + ..... + Aiixi = bi

donde se cumple:

A11x1 = b1
A21x1 + A22x2 = b2

A partir de dicha ecuación, es posible despejar xi:

xi = (bi - sumatoria de j = 1 a i-1 de Aijxj) / Aii

In [ ]:
#PUNTO 6 (TEORICO)

Nuevamente partiendo desde el mismo sistema Ax = b pero en este caso, A es un matriz diagonal superior.

Cada dila del sistema tiene la forma: Ai,ixi + Ai,i+1xi+1 + .... + Ai,nxn = bi

Reordenando la ecuación obtenemos:

Aiixi = bi - sumatoria de j = i+1 hasta n de Aijxj

despejando xi:

xi = (bi - sumatoria de j = i+1 hasta n de Aijxj)/Aii

In [ ]:
#PUNTO 8

In [ ]:
def descomposicion_LU(A):

    n = A.shape[0]
    L = np.eye(n)
    U = A.copy()

    for i in range(n):
        for j in range(i+1, n):
            coeficiente = U[j, i] / U[i, i]
            L[j, i] = coeficiente
            U[j, :] = U[j, :] - coeficiente * U[i, :]

    return L, U

A = np.array([[4., -2., 1.],
              [20., -7., 12.],
              [-8., 13., 21.]])

L, U = descomposicion_LU(A)
L, U

(array([[ 1.,  0.,  0.],
        [ 5.,  1.,  0.],
        [-2.,  3.,  1.]]),
 array([[ 4., -2.,  1.],
        [ 0.,  3.,  7.],
        [ 0.,  0.,  2.]]))